# Generated by Django 3.0.7 on 2020-10-22 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cuisines',
            fields=[
                ('cuisines_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cuisines_name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ingredients',
            fields=[
                ('ingredient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ingredient_name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='recipes',
            fields=[
                ('recipe_id', models.IntegerField(primary_key=True, serialize=False)),
                ('recipe_name', models.TextField(unique=True)),
                ('cooking_method', models.TextField(unique=True)),
                ('image', models.TextField(null=True)),
                ('string_ingredients', models.TextField()),
                ('prep_time', models.IntegerField(null=True)),
                ('serving', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('tag_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tag_name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.TextField(unique=True)),
                ('password', models.TextField()),
                ('email', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='recipe_cuisines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisines_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.cuisines')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipes')),
            ],
        ),
        migrations.CreateModel(
            name='user_recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipes')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.users')),
            ],
            options={
                'unique_together': {('recipe_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='recipe_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipes')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.tags')),
            ],
            options={
                'unique_together': {('recipe_id', 'tag_id')},
            },
        ),
        migrations.CreateModel(
            name='recipe_ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredients')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipes')),
            ],
            options={
                'unique_together': {('recipe_id', 'ingredient_id')},
            },
        ),
    ]
