# Generated by Django 3.1.2 on 2020-10-22 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cuisines',
            fields=[
                ('cuisines_id', models.AutoField(primary_key=True, serialize=False)),
                ('cuisines_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ingredients',
            fields=[
                ('ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='recipes',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(max_length=50)),
                ('cooking_method', models.TextField(unique=True)),
                ('image', models.TextField(null=True)),
                ('string_ingredients', models.TextField()),
                ('prep_time', models.IntegerField(null=True)),
                ('serving', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipes')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.users')),
            ],
        ),
        migrations.CreateModel(
            name='recipe_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipes')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.tags')),
            ],
        ),
        migrations.CreateModel(
            name='recipe_ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredients')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipes')),
            ],
        ),
        migrations.CreateModel(
            name='recipe_cuisines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisines_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.cuisines')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipes')),
            ],
        ),
        migrations.AddConstraint(
            model_name='user_recipes',
            constraint=models.UniqueConstraint(fields=('recipe_id', 'user_id'), name='user_recipes_id'),
        ),
        migrations.AddConstraint(
            model_name='recipe_tags',
            constraint=models.UniqueConstraint(fields=('recipe_id', 'tag_id'), name='recipe_tags_id'),
        ),
        migrations.AddConstraint(
            model_name='recipe_ingredients',
            constraint=models.UniqueConstraint(fields=('recipe_id', 'ingredient_id'), name='recipe_ingredients_id'),
        ),
        migrations.AddConstraint(
            model_name='recipe_cuisines',
            constraint=models.UniqueConstraint(fields=('recipe_id', 'cuisines_id'), name='recipe_cuisines_id'),
        ),
    ]
